sudo: required
dist: trusty
cache:
  directories:
    - "node_modules"
language: node_js
node_js:
  - "4.2.6"

before_script:
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
  - sudo apt install mono-complete -y
  - sudo apt update
  - sudo apt install --install-recommends winehq-devel -y
  - npm install

script:
  npm run build #runs the process to begin building the packages
